### ISSUE TITLE
Doesn't work in KDE Plasma 5

### ISSUE THREAD

**Issue by protist** [rubyAce71697/cricket-score-applet#19]
Hi, I know it's not officially supported, but I just wanted to mention that this doesn't really work in KDE Plasma 5. It seems to install and start okay, but the indicator itself won't expand to show more than one digit. I think this is probably a limitation of Plasma.
![Indicator alone](http://i.imgur.com/tKt92aX.png)

Also, when I hover over the scorecard, it expands to full-screen and the display looks a bit funny.
![Scorecard pop-up](http://i.imgur.com/J9v8XRU.png)

I guess you aren't interested in fixing this, but I'm not sure if you'd like to add this information to the README. Cheers.

**Comment by rawcoder** [comment]
Thanks for reporting this.

We didn't test it on KDE ;)
