### ISSUE TITLE
Cricket Score Indicator

### ISSUE THREAD

**Issue by janpierewiet** [rubyAce71697/cricket-score-applet#21]
In Ubuntu 1404 (updated) the following happens 
After installation you still need to run the command cricscore_indicator from the terminal, which is fine, but then the terminal freezes.  When you then force-quit the terminal the indicator also disappears

**Comment by rawcoder** [comment]
Hmm..., did you try this command: `nohup cricscore_indicator &`?

**Comment by janpierewiet** [comment]
1 With command "nohup cricscore_indicator" the result -
"nohup: ignoring input and appending output to ‘nohup.out’" - indicator appears - terminal freezes - command exit - no response - force-quit terminal - indicator stays on.
2 With command "nohup cricscore_indicator &" the result -
"[1] 14598
nohup: ignoring input and appending output to ‘nohup.out’" - indicator appears - terminal freezes - command exit - terminal closes - indicator stays on.
Thanks for response

**Comment by rawcoder** [comment]
Try running using `Alt-F2` ->  `cricscore_indicator`
This way you won't need to run/close the terminal.

BTW how did you install the app? After PPA installation there should be an entry in the unity dash.
